### ISSUE TITLE
Could you provide Content-length on finish?

### ISSUE THREAD

**Issue by budarin** [AndrewGrachov/koa2-streaming-react-render#3]
I need to monitor how many ifo has been sent to a user but I have not Content-length

**Comment by AndrewGrachov** [comment]
I dont think it is possible, because of response order nature.
So the headers go first, then the body. You cannot know the length until the body is fully flushed, and you cannot send headers after the response body started.

**Comment by budarin** [comment]
I don't need it as Content-length header for a response - I need it for metrics
is there a way to have the size of sent data?

**Comment by AndrewGrachov** [comment]
Are these metrics gathering on the client or on the server?

**Comment by budarin** [comment]
only on the server

**Comment by AndrewGrachov** [comment]
will do today, should be no prob

**Comment by AndrewGrachov** [comment]
https://github.com/AndrewGrachov/koa2-streaming-react-render/pull/4 @budarin 
pls look at it, if its what you need

**Comment by budarin** [comment]
looks great! )

**Comment by AndrewGrachov** [comment]
merged
